In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [2]:
data_train = pd.read_csv("Google_Stock_Price_Train.csv")
data_train.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [3]:
train = data_train.loc[:,["Open"]].values
print(train)

[[325.25]
 [331.27]
 [329.83]
 ...
 [793.7 ]
 [783.33]
 [782.75]]


In [4]:
# Feature Scaling 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))

train_scaled = scaler.fit_transform(train)
print(train_scaled)

[[0.08581368]
 [0.09701243]
 [0.09433366]
 ...
 [0.95725128]
 [0.93796041]
 [0.93688146]]


In [5]:
# create a data structure with 50 timesteps and 1 output

x_train = []
y_train = []
timesteps = 5

for i in range(timesteps, 1258):
    x_train.append(train_scaled[i - timesteps:i, 0])
    y_train.append(train_scaled[i, 0])
x_train, y_train = np.array(x_train), np.array(y_train)

In [6]:
# Reshaping

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
print(x_train)
print(y_train)

[[[0.08581368]
  [0.09701243]
  [0.09433366]
  [0.09156187]
  [0.07984225]]

 [[0.09701243]
  [0.09433366]
  [0.09156187]
  [0.07984225]
  [0.0643277 ]]

 [[0.09433366]
  [0.09156187]
  [0.07984225]
  [0.0643277 ]
  [0.0585423 ]]

 ...

 [[0.96294367]
  [0.96123223]
  [0.95475854]
  [0.95204256]
  [0.95163331]]

 [[0.96123223]
  [0.95475854]
  [0.95204256]
  [0.95163331]
  [0.95725128]]

 [[0.95475854]
  [0.95204256]
  [0.95163331]
  [0.95725128]
  [0.93796041]]]
[0.0643277  0.0585423  0.06568569 ... 0.95725128 0.93796041 0.93688146]


In [ ]:
# Create RNN Model

# Importing the Keras Libraries and packages
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Dropout

# initialisinig the RNN
regressor = Sequential()

# adding the first RNN layer and some Dropout regularisation 
regressor.add(SimpleRNN(units = 100, activation="relu", return_sequences=True ,input_shape = (x_train.shape[1], 1)))

# adding the second RNN layer and some Dropout regularisation 
regressor.add(SimpleRNN(units = 100, activation="relu", return_sequences=True))

# adding the third RNN layer and some Dropout regularisation 
regressor.add(SimpleRNN(units = 100 , activation="relu", return_sequences=True))

# adding the fourth RNN layer and some Dropout regularisation 
regressor.add(SimpleRNN(units = 100))

# Adding thw output Layer
regressor.add(Dense(units=1))

# Compiling the RNN
regressor.compile(optimizer= "adam", loss = "mean_squared_error")

# Fitting the RNN to the Training set
regressor.fit(x_train, y_train, epochs = 50, batch_size = 1)

C:\Users\Rahul Rajpurohit\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 0.0037
Epoch 2/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 0.0011
Epoch 3/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 0.0012
Epoch 4/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 7.9412e-04
Epoch 5/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0012
Epoch 6/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 7.4299e-04
Epoch 7/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 9.0414e-04
Epoch 8/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 8.9953e-04
Epoch 9/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7.4812e-04
Epoch 10/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 8.4779e-04
Epoch 11/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5.3685e-04
Epoch 12/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5.1304e-04
Epoch 13/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5.8265e-04
Epoch 14/50
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - 

In [ ]:
# Getting the real stock price of 2017

data_test = pd.read_csv("Google_Stock_Price_Test.csv")
data_test.head()

In [ ]:
real_stock_price = data_test.loc[:, ["Open"]].values
print(real_stock_price)

In [ ]:
# Getting the predicted stock price of 2017

data_total = pd.concat((data_train["Open"], data_test["Open"]), axis = 0)
inputs = data_total[len(data_total) - len(data_test) - timesteps:].values.reshape(-1,1)
inputs = scaler.transform(inputs) # min max scaler
inputs

In [ ]:
x_test = []
for i in range(timesteps, 70):
    if len(inputs[i-timesteps:i, 0]) == timesteps:
        x_test.append(inputs[i-timesteps:i, 0])

x_test = np.array(x_test)
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
predicte_stock_price = regressor.predict(x_test)
predicte_stock_price = scaler.inverse_transform(predicte_stock_price)

# visualising the results
plt.plot(real_stock_price, color = "red", label = "Real Google Stock Price")
plt.plot(predicte_stock_price, color = "blue", label = "Predicted Google Stock Price")
plt.title("Google Stock Price prediction")
plt.xlabel("Time")
plt.ylabel("Google Stock Price")
plt.legend()
plt.show()